### ISSUE TITLE
How To Re-use This Generator

### ISSUE THREAD

**Issue by soneryaldiz** [ucb-art/skywater130_bag3_sar_adc#1]
How can we install the BAG environment required for this generator to re-use this generator? Could you please provide a cheat sheet including a link to the BAG3 framework to be used?

**Comment by soneryaldiz** [comment]
The [link](https://github.com/ucb-art/bag3_skywater130_workspace) provided in README doesn't exist.

**Comment by FeliciaG** [comment]
I've just added you to the workspace template repo (which is still private). We are currently working on an official release of BAG3, though there should be information on the necessary dependencies that you will need to install independently. If you would like to try it out please feel free.

**Comment by soneryaldiz** [comment]
Thanks! I will wait for the official release. Could you please update this issue when it is released?

**Comment by FeliciaG** [comment]
Will do!

**Comment by FeliciaG** [comment]
The BAG3 documentation and some basic tutorials are now up. You can look at the ReadtheDocs[ here ](https://bag3-readthedocs.readthedocs.io/en/latest/index.html). The server setup has been largely untested on external servers though, so please let us know if you have issues with any of the steps or if any of the instructions are not clear. 

This repo has also been refactored since March to follow BAG best practices. You can find the (under works) ReadtheDocs for the SAR generator[ here ](https://bag3-sync-sar-adc.readthedocs.io/en/latest/index.html).

**Comment by soneryaldiz** [comment]
Thanks @FeliciaG for the update.
